import express from 'express';
import * as authController from '../controllers/authController.js';
import { protect } from '../middleware/auth.js';
const router = express.Router();
router.post('/register', authController.register);
router.post('/login', authController.login);
router.post('/google', authController.googleAuth);
router.post('/refresh', authController.refresh);
router.post('/logout', protect, authController.logout);
router.get('/session', authController.getSession);
router.get('/me', protect, authController.getMe);
export default router;