import express from 'express';
import * as orderController from '../controllers/orderController.js';
import { protect, authorize } from '../middleware/auth.js';
const router = express.Router();
router.use(protect);
router.post('/', orderController.createOrder);
router.get('/', orderController.getOrders);
router.get('/:id', orderController.getOrder);
router.patch('/:id/status', authorize('seller', 'admin'), orderController.updateStatus);
export default router;